import { theme } from "@/theme";
import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  headerContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    marginBottom: 20,
    backgroundColor: "#FFF",
    paddingBottom: 20,
  },
  pageTitle: {
    ...theme.typography.h2,
    color: theme.colors.textPrimary,
    marginBottom: 20,
  },
  userCard: {
    padding: 20,
    borderRadius: 16,
    elevation: 4,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  userInfo: { flexDirection: "row", alignItems: "center" },
  avatarContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  userName: { fontSize: 18, fontWeight: "700", color: "#FFF", marginBottom: 4 },
  userEmail: { fontSize: 13, color: "rgba(255,255,255,0.9)", marginBottom: 8 },
  roleBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  roleText: { color: "#FFF", fontSize: 11, fontWeight: "600", marginLeft: 4 },
  section: { marginBottom: 24, paddingHorizontal: 20 },
  sectionHeader: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.textSecondary,
    marginBottom: 10,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  cardContainer: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  itemContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
  },
  itemLeft: { flexDirection: "row", alignItems: "center", flex: 1 },
  iconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  itemTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: theme.colors.textPrimary,
    marginBottom: 2,
  },
  itemSubtitle: { fontSize: 12, color: theme.colors.textSecondary },
  itemRight: { flexDirection: "row", alignItems: "center" },
  divider: { height: 1, backgroundColor: "#F1F5F9", marginLeft: 68 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  cameraItemContainer: { backgroundColor: "#FFF" },
  permissionStatusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 12,
    paddingLeft: 68,
    marginTop: -8,
  },
  permissionLabel: { fontSize: 12, color: theme.colors.textSecondary },
});
