import { theme } from "@/theme";
import { Dimensions, Platform, StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    gap: 12,
  },
  backBtn: { padding: 4 },
  headerTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  headerSubtitle: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  scrollContent: { padding: 20 },
  instructionBanner: {
    flexDirection: "row",
    backgroundColor: "#E3F2FD",
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  instructionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1E3A8A",
    marginBottom: 4,
  },
  instructionText: { fontSize: 12, color: "#334155", lineHeight: 18 },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 8,
    marginTop: 16,
  },
  required: { color: theme.colors.danger },

  // --- DROPDOWN STYLES ---
  dropdown: {
    height: 50,
    borderColor: "#E5E7EB",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 8,
    backgroundColor: "white",
  },
  icon: { marginRight: 10 },
  placeholderStyle: { fontSize: 14, color: "#9CA3AF" },
  selectedTextStyle: { fontSize: 14, color: theme.colors.textPrimary },
  iconStyle: { width: 20, height: 20 },
  inputSearchStyle: { height: 40, fontSize: 14, borderRadius: 8 },
  dropdownItem: {
    padding: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  textItem: { flex: 1, fontSize: 14, color: theme.colors.textPrimary },

  typeRow: { flexDirection: "row", gap: 10 },
  typeButton: {
    flex: 1,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    alignItems: "center",
    backgroundColor: "#FFF",
  },
  typeButtonActive: {
    backgroundColor: theme.colors.danger,
    borderColor: theme.colors.danger,
  },
  typeText: { fontSize: 12, color: "#6B7280" },
  typeTextActive: { color: "#FFF", fontWeight: "600" },

  row: { flexDirection: "row" },
  dateInput: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    padding: 12,
    backgroundColor: "#FFF",
    gap: 8,
  },
  dateText: { fontSize: 14, color: "#374151" },
  textArea: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    padding: 12,
    height: 100,
    textAlignVertical: "top",
    fontSize: 14,
    color: theme.colors.textPrimary,
    backgroundColor: "#FFF",
  },
  charCount: {
    fontSize: 11,
    color: "#9CA3AF",
    textAlign: "right",
    marginTop: 4,
  },
  photoBox: {
    width: 100,
    height: 100,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderStyle: "dashed",
    position: "relative", // Để định vị nút sửa
  },
  photoText: { fontSize: 11, color: "#6B7280", marginTop: 4 },
  photoPreview: { width: "100%", height: "100%", borderRadius: 8 },
  editBadge: {
    position: "absolute",
    bottom: -5,
    right: -5,
    backgroundColor: theme.colors.primary,
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFF",
  },
  techCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  avatarText: { color: "#FFF", fontWeight: "700" },
  techName: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.textPrimary,
  },
  techRole: { fontSize: 12, color: theme.colors.textSecondary },
  saveBtn: {
    flexDirection: "row",
    backgroundColor: "#CBD5E1",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  saveBtnText: { color: "#FFF", fontWeight: "700", fontSize: 16 },
  errorMsg: {
    color: theme.colors.danger,
    fontSize: 11,
    textAlign: "center",
    marginTop: 8,
  },
});
